### ISSUE TITLE
CT3 database not compatible with the newest mmseqs version

### ISSUE THREAD

**Issue by konsternacjaa** [mtisza1/Cenote-Taker3#11]
Description:
I am encountering an issue where the tool execution stops and works endlessly ('time update: running mmseqs2 against CDD with ORFs not annotated with HMMs') when using versions 15-6f452 and 14-7e284 of mmseqs2. However, the issue does not occur when using version 13-45111, where everything works as expected.

Steps to Reproduce:

1. Install mmseqs2 version 15-6f452 or 14-7e284.
2. Run the tool with the same input data that works with version 13-45111.
3. Observe that the tool execution stops and does not proceed further, effectively hanging indefinitely.

Expected Behavior:
The tool should complete execution successfully, similar to how it behaves with version 13-45111.

Actual Behavior:
The tool execution hangs indefinitely with no error message, requiring a manual termination.

**Comment by mtisza1** [comment]
Hi thanks for opening this issue.

I'm going to look into this more in depth later, but I wanted to give a quick answer based on a hunch.

I noticed that mmseqs2 will not work unless the database is created and queried with the same version of mmseqs2.

If you want to use the newer version of mmseqs2, try reinstalling/creating the `Cenote-Taker 3` DBs with that new mmseqs2 version (change `-o ct3_DBs` to your database directory).

`get_ct3_dbs -o ct3_DBs --hallmark_tax T --refseq_tax T --mmseqs_cdd T`

**Comment by konsternacjaa** [comment]
It works! It turns out I was downloading a database with an older version of mmseqs than CT3 was using... After reinstalling it correctly everything runs as supposed to! Sorry for bothering you

**Comment by mtisza1** [comment]
No bother at all. I'm glad it worked! I'm considering opening an issue on mmseqs2, so they are aware.
