### ISSUE TITLE
Cannot get code to run. 

### ISSUE THREAD

**Issue by jessquaas4** [mtisza1/Cenote-Taker3#16]
Hello, 

I'm trying to run Cenote-Taker3 on my Mac and this issue continues to pop up.

The following package could not be installed
└─ cenote-taker3 is not installable because it requires
   └─ hhsuite, which does not exist (perhaps a missing channel).

I was wondering if you had any suggestions on how to work around this. I have tried a fair few ways to troubleshoot and have had no luck unfortunately. 

Thank you, 
Jess

**Comment by mtisza1** [comment]
Hi Jess,

Thanks for opening the issue. I'm going to guess that you are trying to install `Cenote-Taker 3` on a Windows PC. Unfortunately, this won't work on a Windows OS, and you need a Mac OS or Linux OS machine to install some of the required packages.

If you are getting this error on a Mac or Linux machine, please copy the full error from the terminal and I'll take a look.

Best,

Mike

**Comment by jessquaas4** [comment]
Hi Mike, 

Thank you for your quick reply. I'm using a MacBook Air (M1, 2020). I've tried installing it through Mamba and Conda. Both show up with similar errors. I'll paste both below. 

Thank you, 
Jess

**Mamba**

(base) jessquaas4@Jessicas-Air-2 ~ % mamba create -n ct3_env -c conda-forge -c bioconda cenote-taker3

Looking for: ['cenote-taker3']

warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/a850f475.json" was modified by another program
warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/09cdf8bf.json" was modified by another program
warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/9e99ffaf.json" was modified by another program
pkgs/main/osx-arm64 (check zst)                     Checked  0.2s
warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/3e39a7aa.json" was modified by another program
pkgs/main/noarch (check zst)                       Checked  0.0s
warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/8bd55712.json" was modified by another program
pkgs/r/osx-arm64 (check zst)                       Checked  0.0s
warning  libmamba Cache file "/opt/miniconda3/pkgs/cache/4ea078d6.json" was modified by another program
pkgs/r/noarch (check zst)                          Checked  0.0s
bioconda/osx-arm64                                  42.3kB @  41.0kB/s  1.0s
pkgs/main/osx-arm64                                  2.7MB @   1.6MB/s  1.7s
pkgs/r/osx-arm64                                   108.0 B @  62.0 B/s  0.1s
pkgs/main/noarch                                   716.2kB @ 224.6kB/s  2.2s
pkgs/r/noarch                                        2.1MB @ 534.3kB/s  2.1s
bioconda/noarch                                      4.3MB @ 563.2kB/s  7.7s
conda-forge/osx-arm64                               11.8MB @   1.1MB/s 11.2s
conda-forge/noarch                                  16.4MB @   1.3MB/s 12.2s
Could not solve for environment specs
The following package could not be installed
└─ cenote-taker3 is not installable because it requires
   └─ hhsuite, which does not exist (perhaps a missing channel).

**Conda**

(base) jessquaas4@Jessicas-Air-2 ~ % conda create -n ct3_env -c conda-forge -c bioconda cenote-taker3
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides hhsuite needed by cenote-taker3-3.2.0-pyhdfd78af_0

Could not solve for environment specs
The following package could not be installed
└─ cenote-taker3 is not installable because it requires
   └─ hhsuite, which does not exist (perhaps a missing channel).

**Comment by mtisza1** [comment]
Hi Jess,

I've had a think about this and I believe I've solved it. `hhsuite` is only compatible with Mac platform `osx-64` but not `osx-arm64` (you have `osx-arm64` set).

Fortunately, in more recent versions of `conda` and `mamba`, they have added the `--platform` flag, which allows you to use `osx-64` even if you have the M1 chip. So here's what you need to do on the terminal:

(in case you are using older versions of mamba and conda)
```
mamba install conda=24.7.1
```
check versions, should be at least these:
```
mamba --version 
```

#mamba 1.5.8
#conda 24.7.1

Then install `cenote-taker3` (I noticed your install was defaulting to 3.2.0, so let's specify the newer version)

```
mamba create --platform osx-64 -n ct3_env -c conda-forge -c bioconda cenote-taker3=3.3.1
```

Please let me know if this fixes your issue.

Mike

**Comment by jessquaas4** [comment]
Hi Mike, 

That fixed my issue and I've got the code to run now. 
Thank you so much!

Jess

PS: I also had the same problem as F4NG666 with prodigal-gv not showing up as installed. The code below solved my issue too.
pip uninstall pyrodigal-gv
pip install pyrodigal-gv==0.3.1
